import sqlite3
import os
import shutil
from pathlib import Path

def export_chrome_cookies(output_file='cookies.txt'):
    """
    Export Chrome cookies to Netscape format for yt-dlp
    Make sure Chrome is CLOSED before running this!
    """
    
    # Chrome cookie database path (Windows)
    chrome_path = os.path.expanduser('~') + r'\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies'
    
    # Check if Chrome is installed
    if not os.path.exists(chrome_path):
        print("❌ Chrome cookies not found!")
        print("   Path tried:", chrome_path)
        print("\n💡 Make sure Chrome is installed and you have logged into:")
        print("   - Pinterest")
        print("   - Instagram")
        print("   - Threads")
        return False
    
    print(f"✅ Found Chrome cookies at: {chrome_path}")
    print("\n⚠️  IMPORTANT: Close Chrome completely before continuing!")
    print("   Press Enter when Chrome is closed...")
    input()
    
    # Create a copy since Chrome locks the file when open
    temp_copy = 'cookies_copy.sqlite'
    
    try:
        shutil.copy2(chrome_path, temp_copy)
        print("✅ Copied cookie database")
    except PermissionError:
        print("❌ Cannot copy cookies - Chrome is still open!")
        print("   Please close Chrome completely and try again.")
        return False
    except Exception as e:
        print(f"❌ Error copying: {e}")
        return False
    
    try:
        # Connect to the copied database
        conn = sqlite3.connect(temp_copy)
        cursor = conn.cursor()
        
        # Domains we need cookies for
        domains = ['pinterest.com', 'instagram.com', 'threads.net', 'youtube.com']
        all_cookies = []
        
        for domain in domains:
            cursor.execute(
                "SELECT host_key, name, value, path, expires_utc, is_secure, is_httponly "
                "FROM cookies WHERE host_key LIKE ?", 
                (f'%{domain}%',)
            )
            cookies = cursor.fetchall()
            if cookies:
                print(f"   Found {len(cookies)} cookies for {domain}")
                all_cookies.extend(cookies)
            else:
                print(f"   ⚠️  No cookies found for {domain}")
        
        if not all_cookies:
            print("\n❌ No cookies found!")
            print("   Make sure you are logged into these sites in Chrome:")
            print("   - https://pinterest.com")
            print("   - https://instagram.com")
            print("   - https://threads.net")
            conn.close()
            os.remove(temp_copy)
            return False
        
        # Write in Netscape format
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# https://curl.se/docs/http-cookies.html\n")
            f.write("# This file was generated by export_cookies.py\n")
            f.write("#\n")
            f.write("# Login required for:\n")
            f.write("# - Pinterest\n")
            f.write("# - Instagram\n")
            f.write("# - Threads\n")
            f.write("#\n\n")
            
            for cookie in all_cookies:
                host, name, value, path, expires, secure, httponly = cookie
                
                # Skip if host starts with . or not
                if not host.startswith('.'):
                    host = '.' + host if '.' in host else host
                
                # Convert Chrome timestamp to Unix timestamp
                if expires and expires > 0:
                    # Chrome uses microseconds since 1601-01-01
                    # Convert to seconds since 1970
                    expires_seconds = int((expires / 1000000) - 11644473600)
                    expires_str = str(expires_seconds)
                else:
                    expires_str = "0"
                
                secure_flag = "TRUE" if secure else "FALSE"
                
                f.write(f"{host}\tTRUE\t{path}\t{secure_flag}\t{expires_str}\t{name}\t{value}\n")
        
        conn.close()
        os.remove(temp_copy)
        
        print(f"\n✅ SUCCESS! Cookies exported to: {output_file}")
        print(f"   File size: {os.path.getsize(output_file)} bytes")
        print(f"   Total cookies: {len(all_cookies)}")
        return True
        
    except Exception as e:
        print(f"❌ Error: {e}")
        if os.path.exists(temp_copy):
            os.remove(temp_copy)
        return False

if __name__ == "__main__":
    print("\n" + "="*50)
    print("   🍪 Chrome Cookie Exporter for yt-dlp")
    print("="*50 + "\n")
    
    result = export_chrome_cookies('cookies.txt')
    
    if result:
        print("\n📌 Next steps:")
        print("   1. Run: node server.js")
        print("   2. Test Pinterest download")
    else:
        print("\n💡 Troubleshooting:")
        print("   1. Make sure Chrome is CLOSED completely")
        print("   2. Check Task Manager for chrome.exe processes")
        print("   3. Login to Pinterest, Instagram, Threads in Chrome")
        print("   4. Then run this script again")
    
    input("\nPress Enter to exit...")